#!/usr/bin/env python3
import socket

def main():
    target = input("Enter target IP: ")
    
    #List of ports to scan
    ports = [21, 22, 23, 25, 53, 80, 443]

    print(f"Scanning {target}...")

    for port in ports:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1) # 1 second timeout


        result = s.connect_ex((target, port))

        if result == 0:
            print(f"[+] Port {port} is OPEN")
        else:
            print(f"[-] Port {port} is CLOSED")

        s.close()

if __name__ == "__main__":
    main()
